
image: ubuntu:22.04


stages:          # List of stages for jobs, and their order of execution
  - build

vale-linting:
  image:
    name: jdkato/vale:latest
    entrypoint: [""]
  stage: build
  allow_failure: true  
  before_script:
    - apk update && apk add git
  script:
    - git clone https://gitlab-ci-token:${CI_JOB_TOKEN}@gitlab-ee.dev.ifm/syntron/support/csr/formatting-tools.git ${CI_PROJECT_DIR}/formatting-tools
    - cd ${CI_PROJECT_DIR}/formatting-tools
    - vale --minAlertLevel error ../ovp8xx ../README.md


