version: "2.4"

services:

  deepstream:
    image: nvcr.io/nvidia/deepstream-l4t:5.1-21.02-samples
    container_name: deepstream
    entrypoint: /usr/src/tensorrt/bin/trtexec --onnx=/home/oem/share/yolov4-tiny.onnx --batch=1 --verbose
#  --useSpinWait
# --batch=1
# --allowGPUFallback
# --useDLACore=0
# --useDLACore=1
# --useDLACore=2
# --useDLACore=3
# --int8
# --dumpProfile
# --exportTimes
# --verbose
# --help
    runtime: nvidia

    # It is reccommended to limit connectivity to a specific port, however some interfaces such as CAN may require future updates to run via docker container without network_mode: host  
    # network_mode: host
    # ports:
    #   - 8000:8000

    # stdin_open: true

    # If the container crashes it should be restarted
    restart: unless-stopped
    
    # In production, use this logging config to avoid hammering ssd with excessive writes
    # comment out these lines to immediately see output of container in console when running docker-compose up
    # logging:
    #   driver: "none"

    environment:
      - ON_VPU=1

    volumes:
      - oemshare:/home/oem/share/

# Shared directory between the container and VPU host
volumes:
  oemshare:
    external: true