services:
  ifm3dlab:
    command: '"python3 /home/oem/share/ifm3d-examples/ovp8xx/docker/packages/ifm3d/python_logging.py"'
    container_name: ifm3dlab
    cpuset: 0,3,4,5
    entrypoint: /bin/bash -c
    environment:
    - ON_OVP=1
    - IFM3D_IP=172.17.0.1
    image: l4t-ifm3dlab:0.0.0-arm64
    network_mode: host
    restart: unless-stopped
    runtime: nvidia
    volumes:
    - /home/oem/share/:/home/oem/share/
    working_dir: /home/oem/share
version: '2.4'
