services:
  ifm3dlab:
    command: '"/start_jupyter && python3 /home/oem/share/ifm3d-examples/ovp8xx/docker/packages/ovp_recorder/ifm_o3r_algodebug/http_api.py
      && python3 -c \"exec(''import time\nimport ifm3dpy\nfor x in range(int(1e10)):\n    print(f\\\''ifm3dpy=={ifm3dpy.__version__}\\\'')\n    time.sleep(5)'')\""'
    container_name: ifm3dlab
    cpuset: 0,3,4,5
    entrypoint: /bin/bash -c
    environment:
    - ON_OVP=1
    - IFM3D_IP=172.17.0.1
    - JUPYTER_PORT=8888
    - JUPYTER_PASSWORD=ifm3dlab
    - JUPYTER_ROOT=/
    - JUPYTER_LOGS=/home/oem/share/jupyter.log
    image: l4t-ifm3dlab-docke-jupyt-ovp_r-ifm3d:0.0.0-arm64
    network_mode: host
    restart: unless-stopped
    runtime: nvidia
    volumes:
    - /home/oem/share/:/home/oem/share/
    - /var/run/docker.sock:/var/run/docker.sock
    - /run/media/system/ovp8xx_usb:/run/media/system/ovp8xx_usb
    working_dir: /home/oem/share
version: '2.4'
